revise logic for downloading & verifying images

diff --git a/overlay/usr/share/lxc/templates/lxc-turnkey b/overlay/usr/share/lxc/templates/lxc-turnkey
--- a/overlay/usr/share/lxc/templates/lxc-turnkey
+++ b/overlay/usr/share/lxc/templates/lxc-turnkey
@@ -44,6 +44,7 @@ ARCHIVE_MIRROR=${ARCHIVE_MIRROR:-http://archive.turnkeylinux.org/debian}
 LOCALSTATEDIR="/var"
 LXC_TEMPLATE_CONFIG="/usr/share/lxc/config"
 LEASES="/var/lib/misc/dnsmasq.leases"
+TMP="/tmp"
 
 info() { echo "INFO [$(basename $0)]: $@"; }
 warn() { echo "WARN [$(basename $0)]: $@" 1>&2; return 1; }
@@ -203,28 +204,38 @@ configure_debian_systemd() {
 }
 
 verify_signature() {
-    local cache=$1
-    local image=$2
-    local sig=${cache}/${image}.${ext}
+    local location="$1"
+    local image="$2"
+    local signature="$3"
     local keyid="A16EB94D"
     local keyring="/etc/apt/trusted.gpg.d/turnkey.gpg"
 
+    [ ! -f "${location}/${image}" ] && fatal "image ${location}/${image} not found"
+    [ ! -f "${location}/${signature}" ] && fatal "signature ${location}/${signature} not found"
+
     if [[ "${image}" =~ "debian-7" ]]; then
         info "verifying image..."
-        gpg --keyring ${keyring} --verify ${sig} ${cache}/${image}
+        gpg --keyring ${keyring} --verify ${location}/${signature} ${location}/${image}
     else
         info "verifying gpg signature..."
-        gpg --keyring ${keyring} --verify ${sig}
+        gpg --keyring ${keyring} --verify ${location}/${signature}
         if [ $? -ne 0 ]; then  
-            fatal "${image}.${ext} gpg verification failed"
+            fatal "${signature} gpg verification failed"
         fi
 
         info "verifying checksum..."
-        sum1=$(sha1sum  ${cache}/${image} | cut -d " " -f 1)
-        sum2=$(grep -A 1 sha1sum ${sig} | tail -n 1 | sed "s/^ *//")
-        if [ ! "$sum1" == "$sum2" ]; then
-            fatal "${image} checksum verification failed"
+        cd ${location}
+        if [[ "${signature}" =~ ".sig" ]]; then
+            sum=$(grep -A 1 sha1sum ${signature} | tail -n 1 | sed "s/^ *//")
+            echo "${sum} ${image}" | sha1sum --status -c -
+            [ $? -ne 0 ] && fatal "${image} checksum verification failed"
+        elif [[ "${signature}" =~ ".hash" ]]; then
+            sha512sum --status -c "${signature}"
+            [ $? -ne 0 ] && fatal "${image} checksum verification failed"
+        else
+            fatal "${signature} unknown checksum type"
         fi
+        cd -
     fi
 
     info "verified successfully"
@@ -232,12 +243,10 @@ verify_signature() {
 }
 
 cleanup() {
-    local cache=$1
-    local image=$2
-
-    rm -rf ${cache}/${image}.tmp
-    rm -rf ${cache}/${image}.${ext}
-    rm -rf ${cache}/${image}
+    info "removing temporary files..."
+    rm -f ${TMP}/${image}
+    rm -f ${TMP}/${signature}
+    return 0
 }
 
 get_image_name() {
@@ -250,39 +259,43 @@ get_image_name() {
     echo ${name}
 }
 
+download_signature() {
+    info "downloading appliance signature..."
+    wget --read-timeout=10 -t 3 -nv -c ${baseurl}/${signature} -O ${TMP}/${signature}
+    if [ $? -ne 0 ]; then
+        verify_signature ${cache} ${image} ${signature}
+    elif cmp -s "${TMP}/${signature}" "${cache}/${signature}" ; then
+        info "no change in appliance signature...using cached image..."
+        if [ -f "${cache}/${image}" ]; then
+            verify_signature ${cache} ${image} ${signature}
+        else
+            download_image
+        fi
+    else
+        download_image
+    fi
+    cleanup
+    return 0
+}
+
 download_image() {
-    local cache=$1
-    local version=$2
-    local image=$3
+    # make sure that signature file has been downloaded to ${TMP}
+    [ ! -f "${TMP}/${signature}" ] && fatal "signature ${TMP}/${signature} not found"
 
     info "downloading appliance image..."
-    mkdir -p ${cache}
-    if [ "${version}" == "13.0-wheezy" ]; then
-      imagesurl="${TURNKEY_MIRROR}/images/openvz"
+    wget --read-timeout=10 -t 3 -nv -c ${baseurl}/${image} -O ${TMP}/${image}
+    if [ $? -eq 0 ]; then
+        verify_signature ${TMP} ${image} ${signature}
+        mv ${TMP}/${image} ${cache}/${image}
+        mv ${TMP}/${signature} ${cache}/${signature}
     else
-      imagesurl="${TURNKEY_MIRROR}/images/proxmox"
-    fi
-    wget --read-timeout=10 -t 3 -c ${imagesurl}/${image} -O ${cache}/${image}.tmp
-    if [ $? -ne 0 ]; then
-        cleanup ${cache} ${image}
+        cleanup
         fatal "failed to download '${image}'"
-    else
-        mv ${cache}/${image}.tmp ${cache}/${image}
-        wget --read-timeout=10 -t 3 -c ${imagesurl}/${image}.${ext} -O ${cache}/${image}.${ext}
-        return $?
     fi
+    return 0
 }
 
 extract_image() {
-    local cache=$1
-    local image=$2
-    local rootfs=$3
-
-    # if signature file exists, verify image
-    if [ -f ${cache}/${image}.${ext} ]; then
-        verify_signature ${cache} ${image}
-    fi
-
     info "extracting appliance image..."
     mkdir -p ${rootfs}
     tar --numeric-owner -zxf ${cache}/${image} -C ${rootfs}/
@@ -330,9 +343,6 @@ configure_turnkey() {
 }
 
 install_turnkey() {
-    local cache="$LOCALSTATEDIR/cache/lxc/turnkey"
-    local image=$1
-    local rootfs=$2
 
     mkdir -p $LOCALSTATEDIR/lock/subsys/
     (
@@ -342,12 +352,8 @@ install_turnkey() {
             return 1
         fi
 
-        info "checking cache download in ${cache}/${image} ... "
-        if [ ! -e "${cache}/${image}" ]; then
-            download_image ${cache} ${version} ${image}
-        fi
-
-        extract_image ${cache} ${image} ${rootfs}
+        download_signature
+        extract_image
 
         return 0
 
@@ -441,8 +447,6 @@ EOF
 }
 
 clean() {
-    local cache="$LOCALSTATEDIR/cache/lxc/turnkey"
-
     if [ ! -e ${cache} ]; then
         exit 0
     fi
@@ -578,13 +582,22 @@ if [ -z "${rootfs}" ]; then
     rootfs=${rootfs:-${path}/rootfs}
 fi
 
+if [ "${version}" == "13.0-wheezy" ]; then
+    baseurl="${TURNKEY_MIRROR}/images/openvz"
+else
+    baseurl="${TURNKEY_MIRROR}/images/proxmox"
+fi
+
+cache="$LOCALSTATEDIR/cache/lxc/turnkey"
+mkdir -p ${cache}
+
 image=$(get_image_name ${deb_version} ${app_name} ${tkl_version} ${arch})
 
 case "${tkl_version}" in
-    13.0)	ext="sig";;
-    14.0)	ext="sig";;
-    14.1)	ext="sig";;
-       *)	ext="hash";;
+    13.0)	signature="${image}.sig";;
+    14.0)	signature="${image}.sig";;
+    14.1)	signature="${image}.sig";;
+       *)	signature="${image}.hash";;
 esac
 
 install_turnkey ${image} ${rootfs}
